version: '3.8'

services:
  server:
    build: .
    platform: linux/x86_64
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
